[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "requests >= 2.32.3",
  "rich >= 14.0.0",
  "scikit-image >= 0.25.2",
  "colorthief >= 0.2.1",
  "fastmcp>=2.7.1",
]
